[package]
name = "multiplexer"
version = "0.1.0"
edition = "2021"

[dependencies]
alloy = { version="0.2.1", features = ["full", "node-bindings"] }
tokio = "1.39.3"

[lib]
name = "multiplexer"
path = "src/multiplexer.rs"
